name: General Assignment
# run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # загружаем реп. на виртуальную машину
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4 # установка SDK для сборки, тестирования и тд. проекта.
      with:
        dotnet-version: '6.0.x'

    - name: Restore NuGet
      run: dotnet restore WpfApp.sln # восставновление пакетов nuget

    - name: Build
      run: dotnet test UnitTestProject1/UnitTestProject1.csproj # собираем проект

  finish:  
    runs-on: ubuntu-latest
    needs: build
    steps:
    - run: echo "Проект успешно выгружен"
